# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Disable style-only rules
    avoid_print: false  # Allow print for debugging
    constant_identifier_names: false  # Allow SCREAMING_CAPS for constants
    file_names: false  # Allow flexible file naming
    use_key_in_widget_constructors: false  # Allow widgets without key parameter
    prefer_const_constructors_in_immutables: false  # Allow non-const constructors
    unnecessary_this: false  # Allow 'this.' qualifier
    use_super_parameters: false  # Allow traditional parameter passing
    library_private_types_in_public_api: false  # Allow private types in public API
    annotate_overrides: false  # Allow missing @override annotations
    
    # Disable non-critical behavioral rules
    use_build_context_synchronously: false  # Allow BuildContext across async gaps
    sort_child_properties_last: false  # Allow flexible property ordering
    sized_box_for_whitespace: false  # Allow Container for whitespace
    prefer_interpolation_to_compose_strings: false  # Allow string concatenation
    use_rethrow_when_possible: false  # Allow throw e instead of rethrow

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
