// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_DKyMEb2PK2cHKzELm8OG3xtNzXQB6J4',
    appId: '1:754104813353:web:13faef91c05db292d49938',
    messagingSenderId: '754104813353',
    projectId: 'test-f85bb',
    authDomain: 'test-f85bb.firebaseapp.com',
    storageBucket: 'test-f85bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IRfYruqBYUWWGfhNYVL1T-t6TXdYGW0',
    appId: '1:754104813353:android:36771fee8aba1dcfd49938',
    messagingSenderId: '754104813353',
    projectId: 'test-f85bb',
    storageBucket: 'test-f85bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApBp51kXAusjYrvtl5NGt72K0pqj2C1ek',
    appId: '1:754104813353:ios:b50925314df185c1d49938',
    messagingSenderId: '754104813353',
    projectId: 'test-f85bb',
    storageBucket: 'test-f85bb.appspot.com',
    androidClientId:
        '754104813353-0i4sjj6bpivo5uck4dohr7fp1j3fhmvm.apps.googleusercontent.com',
    iosClientId:
        '754104813353-7lfhd7oqvkv9q5tdghqld1u4d1hgsmum.apps.googleusercontent.com',
    iosBundleId: 'com.example.submission1Expert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApBp51kXAusjYrvtl5NGt72K0pqj2C1ek',
    appId: '1:754104813353:ios:b50925314df185c1d49938',
    messagingSenderId: '754104813353',
    projectId: 'test-f85bb',
    storageBucket: 'test-f85bb.appspot.com',
    androidClientId:
        '754104813353-0i4sjj6bpivo5uck4dohr7fp1j3fhmvm.apps.googleusercontent.com',
    iosClientId:
        '754104813353-7lfhd7oqvkv9q5tdghqld1u4d1hgsmum.apps.googleusercontent.com',
    iosBundleId: 'com.example.submission1Expert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_DKyMEb2PK2cHKzELm8OG3xtNzXQB6J4',
    appId: '1:754104813353:web:e73ee44ae926213ed49938',
    messagingSenderId: '754104813353',
    projectId: 'test-f85bb',
    authDomain: 'test-f85bb.firebaseapp.com',
    storageBucket: 'test-f85bb.appspot.com',
  );
}
